### ISSUE TITLE
Playing with Output Spectrum: Continuum Normalization

### ISSUE THREAD

**Issue by lcjohnso** [jradavenport/spectra#14]
Feature Request: for processed spectrum, perform continuum normalization and plot / export result.  Great for eye-balling features in quick-look outputs!

**Comment by jradavenport** [comment]
This is probably similar to how I would structure such functionality: [norm.pro](http://www.astro.washington.edu/docs/idl/cgi-bin/getpro/library38.html?NORM) 
having option of polynomial or spline fit

And maybe use the [span_selector](http://matplotlib.org/examples/widgets/span_selector.html) widget to make a slick method for either removing or adding regions

**Comment by jradavenport** [comment]
Started to add the basic framework to this today. `mode='poly'` the only working part to fit the continuum model, but should return a normalized spectrum using the equation:

```
norm = (data - model) / model
```

I envision having an interactive mode, and or ability to enter a list of wavelength ranges to define a pseudo-continuum

**Comment by jradavenport** [comment]
@lcjohnso, if you had data to test this, I'd be happy to play with it!

**Comment by jradavenport** [comment]
will just assume my code works perfectly. closing with total hubris
