### ISSUE TITLE
Test: UT140701

### ISSUE THREAD

**Issue by tdwilkinson** [jradavenport/spectra#19]
I have already reduced this data from Fall quarter, and decided to run spectra on it. However, I ran into this error: 

IOError: [Errno 2] No such file or directory: 'apohenear.dat'

I checked the resources directory and did not see this file. Should I download it somewhere?

**Comment by jradavenport** [comment]
the file actually should be [included](https://github.com/jradavenport/spectra/blob/master/resources/linelists/apohenear.dat) but I think i was pointing to it wrong in the code if someone actually entered the default file name.... 

Let me know if it works now!

**Comment by tdwilkinson** [comment]
reminder: add into documentation to put standard image first in objlist.txt

**Comment by jradavenport** [comment]
Have added a new page to the wiki that will explain more about the autoreduce function
https://github.com/jradavenport/spectra/wiki/autoreduce

**Comment by tdwilkinson** [comment]
Thanks! I was just looking for spec50cal list.
