### ISSUE TITLE
Test: UT140701 ; HeNeAr_fit documentation

### ISSUE THREAD

**Issue by tdwilkinson** [jradavenport/spectra#24]
Here's what the documentation states to use:

HeNeAr_file = 'HeNeAr.0030r.fits'
wfit = spectra.HeNeAr_fit(HeNeAr_file, trim=True, fmask=fmask_out,
                          interac=True, mode='poly', fit_order=5)

My Error: NameError: name 'fmask_out' is not defined

I did not see this as a variable in the code, but it is referenced as a fmask=fmask_out throughout the documentation. 

Spectra code:
def HeNeAr_fit(calimage, linelist='apohenear.dat', interac=True,
trim=True, fmask=(1,), display=True,
tol=10, fit_order=2, previous='',mode='poly',
second_pass=True):

So, should this be an array or are we labeling this as a name?

**Comment by tdwilkinson** [comment]
Going to test this without fmask since it is mentioned as optional.

**Comment by jradavenport** [comment]
fmask is the 2nd output from `flatcombine`. It is a 1-d vector that corresponds to the illuminated portion of the chip in the spatial direction. It is totally fine to not pass it to subsequent functions, just make sure you're consistent with it!

Let me know how it goes, and feel free to close the issue if it all works!

**Comment by jradavenport** [comment]
updated the manual reduction guide's description of this
https://github.com/jradavenport/spectra/wiki/Manual-Reduction-Guide

**Comment by tdwilkinson** [comment]
This works great now. I did add quotes around the fmask_out task from the manual to get it to work. 

(HeNeAr_file, trim=True, fmask='fmask_out', interac=True, mode='poly', fit_order=5)

**Comment by jradavenport** [comment]
Hmm, I would have thought that would _not_ work. Let's sit down and check it out today/tomorrow!

**Comment by tdwilkinson** [comment]
Full disclosure, the edit got me to where I could run the code, but did not get all the way through the task. Almost! 

I was able to identify lines. With 7 or so lines identified the fit shown is nice with residuals less than 1 standard deviation. Then, I accepted the polynomial order by pressing d. In the next part, when it was tracing the lines along the y-axis, producing a full 2-d wavelength solution for the image, I was a bit confused at first, as I didn't know how to continue. It states how many peaks are found, and begins a 2nd pass fit over. I did not see how to confirm, adjust, or edit them at this step, and ended up closing the window many times to get past this step. The 2nd pass fit did look good, with okay residuals. 
Unfortunately, after this step is when I found the error:

 ENTER: "d" (done) or a # (poly order): d
Traceback (most recent call last):
  File "identifyscript.py", line 9, in <module>
    wfit = spectra.HeNeAr_fit(HeNeAr_file, trim=True, fmask='fmask_out', interac=True, mode='poly', fit_order=5)
  File "/astro/users/twilki/research/mdwarf/spectra/spectra.py", line 1030, in HeNeAr_fit
    ydata = np.arange(img.shape[0])[fmask]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Here is the spectra code at that line: 
 # the valid y-range of the chip
if (len(fmask)>1):
     ydata = np.arange(img.shape[0])[fmask]
else:
     ydata = np.arange(img.shape[0])

Not sure what the error is about and would like to chat about it.

**Comment by jradavenport** [comment]
Yeah, this error appears to be due to handing it a string instead of an array
