### ISSUE TITLE
Autoreduce output  object.fits.spec

### ISSUE THREAD

**Issue by tdwilkinson** [jradavenport/spectra#26]
These files include commas, which just make it a pain to pull out the data for plotting as they have to be removed. 
In your spectra code (line 100):

fout.write(str(wfinal[k]) + ', ' + str(ffinal[k]) + ', ' + str(efinal[k]) + '\n')

suggestion:  (?)

fout.write(str(wfinal[k]) + '   ' + str(ffinal[k]) + '  ' + str(efinal[k]) + '\n')

(With spaces - possibly not needed)
Would this be okay to implement?

**Comment by jradavenport** [comment]
You should file a pull request! :)
