### ISSUE TITLE
rename back to pyDIS?

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/spectra#29]
It has been suggested to rename this package back to the original working title of "pyDIS", since all the effort has gone in to making it work for the APO 3.5-m DIS data.

Leave a comment if you have any thoughts!

cc: @StellarArmy @tdwilkinson @kolbylyn @jlurie @adleorocks

**Comment by kweis** [comment]
Agreed. Or pySPEC or else...? pyDIS does still sound like something
contagious, but I like it being specific to python/DIS/both

**Comment by adleorocks** [comment]
I always liked pydis and you probably aren't going to spend time to generalize it (soon anyway) and pretty sure no one else will have the name pydis!

**Comment by jradavenport** [comment]
OK, I'm sold, will rename to pyDIS! Links to _SPECTRA_ should automatically redirect...

**Comment by jradavenport** [comment]
Done!
