### ISSUE TITLE
Autoreduce: Dis-high data in blue 

### ISSUE THREAD

**Issue by tdwilkinson** [jradavenport/spectra#36]
First, thanks to your last changes, this a sample of great DIS-high data reduction (in red): 
![kic5597604 16r](https://cloud.githubusercontent.com/assets/11761321/7674452/4187670a-fcdd-11e4-974e-55b7000a9876.png)

It was so quick ! So, I decided to try it with the blue images. The results were... interesting. I ran the pydis.autoreduce the first time with the red henear by accident: 
![kic2285598 11b_r](https://cloud.githubusercontent.com/assets/11761321/7674508/71b54fc2-fcde-11e4-9047-ffbcac2f110b.png)

 The results were off, and I found the error in my code. This is what I got with the blue henear:
![hmmm 15b](https://cloud.githubusercontent.com/assets/11761321/7674505/40c9d004-fcde-11e4-855e-c12dd36b37e2.png)
It seems we have discovered plasma dragons.

I'm not sure why the blue images would reduce differently than the red. I looked in pydis.py and could not find anything. On my side, I double checked my lists, and all seem to be the same. The next DIS-high night I ran with pydis.autoreduce also looked good in the red, and the same distortions appeared in the blue.

**Comment by jradavenport** [comment]
this wacky result is when the HeNeAr gets solved poorly. Consider: you're fitting a polynomial to describe wavelength versus pixel number. That polynomial _could_ turn over and start going back down again, which would cause the spectrum to "double over" on itself. 

Be sure to do the Blue HeNeAr with care! And be careful when fitting to polynomial!

**Comment by jradavenport** [comment]
Are you doing the HeNeAr manually for both the red/blue?

**Comment by tdwilkinson** [comment]
Okay, that makes sense. I was using interact=False, so I was expecting to rerun these to get more robust results anyway.

**Comment by tdwilkinson** [comment]
Whoa.  :)
I was just running the quick autorun script to get through all of the nights of data. Then, I am going to run the red side manually from there.

**Comment by jradavenport** [comment]
It's an interesting bug, i'll create a new issue for it. Not entirely clear to me at the moment how to solve it, but we should impose the condition that wavelength must monotonically change and not turn over!
