### ISSUE TITLE
Clarification in docuemntation

### ISSUE THREAD

**Issue by solontoi** [jradavenport/spectra#38]
I've gotten the autoreduce wrapper to work with my low resolution asteroid data, works really well. There needs to be a clarification on the wiki/instructions as written though, once you've added the pydis directory to the sys.path you should call autoreduce with

> > > import wrappers

and then

> > > wrappers.autoreduce(obj...

since autoreduce is defined in wrappers.py and not pydis.py

**Comment by jradavenport** [comment]
hm weird... here's what I do:

```
import pydis
pydis.autoreduce
```

because `autoreduce` is exposed in `__init__.py`

Maybe my sys.path hack is wrong in the instructions...

**Comment by jradavenport** [comment]
By the way: I'd love to see some of the results you had using it, or any comments on the instructions/results/etc!

**Comment by solontoi** [comment]
Might be it - here's what happens when I try running autoreduce from pydis and then from wrappers:
![out1](https://cloud.githubusercontent.com/assets/6720498/8063431/9f14edc6-0ea2-11e5-8ee0-ae176c9be4bb.png)

I'll post my dodgy asteroid spectra in a moment.

**Comment by jradavenport** [comment]
... hm, what happens if you try this?

```
import pydis-master
```

**Comment by solontoi** [comment]
Python doesn't like me trying to subtract master from pydis :) I solved the issue - copied everything into a directory named pydis inside my observing folder (same structure as before), and ran the following:
![temp2](https://cloud.githubusercontent.com/assets/6720498/8064484/04590c84-0ea9-11e5-9a83-bdd6ffc5ec7c.png)

Since I'm still getting my python feet under me I'm not sure if that wording of your sys.path line was confusing for anyone but me.

**Comment by jradavenport** [comment]
closing as "good enough" 

:)
