### ISSUE TITLE
Test against benchmark data

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/spectra#7]
need to find some benchmark data to test this against! So far it runs for both DIS R1200 and B1200 gratings with good S/N.

How does it do with low-res? Medium S/N?

Can I find some example DIS data I trust to test it on? Maybe binary star stuff from SLH's class?

**Comment by solontoi** [comment]
I've got gobs of low-res asteroid spectra as well as a bunch of solar analog stars using DIS R300 and B400.  The solar analogs should be bog-standard spectra reduction but the asteroids require normalization by a solar spectrum to produce a reflectance spectra, else they pretty just look like a slightly funny sun-like star.

**Comment by jradavenport** [comment]
Awesome! Two options:
1. send me some raw data & final results from your own IRAF reductions
2. maybe try running _SPECTRA_ for me on your data! (or a student, perhaps)

The latter has the added benefit of testing my documentation and default settings

Thoughts?

**Comment by solontoi** [comment]
Sounds good, I'll try to give it a whirl this weekend and let you know what happens.

**Comment by jradavenport** [comment]
be sure to get the latest version, still tweaking lots of things!!

i'll try to add some more comments if i get time, and am hoping to write a short "how to use" on the github wiki page

**Comment by jradavenport** [comment]
Would be great also if @tdwilkinson could help with this :)

**Comment by solontoi** [comment]
Weekend trip report: Almost got it to work, pretty sure I fixed all the dependency issues on my end, but wasn't able to push it through all the way to extraction. Once I get through the Monday madness at work I'll give it another run.  If i'm still hung up @jradavenport do you want the error dump or the files that I'm trying to get to reduce?

**Comment by jradavenport** [comment]
almost working! hah!

I would love a sense for the dependency issues you found, and yes the error dump would be awesome. 

The files themselves would be super useful too. Each time i've tried new data i find new... challenges. :) It might be a case of setting various parameters that i have under-doccumented.

My goal: have a bunch of example datasets with working calls to _SPECTRA_ for people to use as guides for their own data needs!

**Comment by jradavenport** [comment]
Seems to be working on test data that I have on hand. 

If @solontoi or @tdwilkinson have any more they want to try (either by themselves or send to me to try) I am happy to do so, but closing issue for now
