### ISSUE TITLE
Report uncertainties on output spectrum

### ISSUE THREAD

**Issue by ebellm** [jradavenport/spectra#82]
For line fitting, etc., it is helpful to have an estimate of the uncertainty for each point in the spectrum.

**Comment by jradavenport** [comment]
I think `autoreduce`  _does_ produce an error column.
https://github.com/TheAstroFactory/pydis/wiki/function:-autoreduce

I think it's just Poisson though...

**Comment by ebellm** [comment]
Silly me!
